# Generated by Django 3.2.7 on 2021-12-15 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('director', models.CharField(max_length=50)),
                ('avg_rate', models.FloatField(default=0)),
                ('reviews_number', models.IntegerField(default=0)),
                ('released_on', models.DateField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='Platforms.platform')),
            ],
        ),
    ]
